set(SOURCES
	src/Forms/Forms.h
	src/Menus/ContainerMenu/BarterMenu.h
	src/Menus/ContainerMenu/ContainerMenu.h
	src/Menus/ContainerMenu/ContainerMenuBase.h
	src/Menus/HUDMenuEx/HUDMenuEx.h
	src/Menus/InventoryUserUIUtils/InventoryUserUIUtils.h
	src/Menus/LevelUpMenu/LevelUpMenu.h
	src/Menus/LevelUpMenu/PerkManager.h
	src/Menus/Menus.h
	src/Menus/PipboyMenu/PipboyManager.h
	src/Menus/PluginExplorerMenu/PluginExplorer.h
	src/Menus/PluginExplorerMenu/PluginExplorerMenu.h
	src/Menus/Scaleform/Log.h
	src/Menus/Utils/InventoryItemDisplayData/InventoryItemDisplayData.h
	src/Menus/Utils/ItemCard/ItemCard.h
	src/Menus/Utils/ItemSorter/ItemSorter.h
	src/Menus/Utils/Utils.h
	src/PCH.cpp
	src/PCH.h
	src/Settings.h
	src/main.cpp
)
